### ISSUE TITLE
[request] Downloading 

### ISSUE THREAD

**Issue by cualquiercosa327** [jaames/dreams-api#2]
Hello, is any way to could use it without need of know nodejs nor need to install it? 
I mean an app or web where one can easily download? 

Do you know any way to extract and inject them on our  dream copy? 
Thanks!

**Comment by jaames** [comment]
This is a proxy that gets around the auth restrictions on the indreams.me website to fetch details about the levels, it can't get the level data itself. It's a technical tool, therefore it doesnt make sense to provide an "easy" version - it wouldn't have any use for non technical people.

I dont know of any way to inject levels into the game and haven't poked around with it for a long time
